"use client";

import { useEffect, useRef, useState } from "react";
import axios from "axios";
import { Light as SyntaxHighlighter } from "react-syntax-highlighter";
import js from "react-syntax-highlighter/dist/esm/languages/hljs/javascript";
import python from "react-syntax-highlighter/dist/esm/languages/hljs/python";
import cpp from "react-syntax-highlighter/dist/esm/languages/hljs/cpp";
import { atomOneDark } from "react-syntax-highlighter/dist/esm/styles/hljs";
import { saveAs } from "file-saver";
import toast, { Toaster } from "react-hot-toast";

SyntaxHighlighter.registerLanguage("javascript", js);
SyntaxHighlighter.registerLanguage("python", python);
SyntaxHighlighter.registerLanguage("cpp", cpp);

export default function Home() {
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState([]); // {role:'user'|'assistant', text, time}
  const [loading, setLoading] = useState(false);
  const [appendCopyright, setAppendCopyright] = useState(true);
  const [selectedTemplate, setSelectedTemplate] = useState("");
  const bottomRef = useRef(null);

  // prompt templates
  const templates = [
    { id: "gen_func", label: "Generate Function", prompt: "Write a concise, well-documented function in {lang} to {task}." },
    { id: "explain", label: "Explain Code", prompt: "Explain the following code and time complexity: {code}" },
    { id: "refactor", label: "Refactor", prompt: "Refactor this code for readability and performance: {code}" },
    { id: "bugfix", label: "Find Bug", prompt: "Identify bugs in this code and provide fixed version: {code}" },
  ];

  useEffect(() => {
    // autopaste sample welcome message once
    if (messages.length === 0) {
      setMessages([
        { role: "assistant", text: "Welcome to Kavish AI — a developer assistant. Try 'Generate a Python function to sort an array' or choose a template.", time: new Date() }
      ]);
    }
  }, [messages.length]);

  useEffect(() => bottomRef.current?.scrollIntoView({ behavior: "smooth" }), [messages, loading]);

  function pushMessage(role, text) {
    setMessages(prev => [...prev, { role, text, time: new Date() }]);
  }

  function extractCodeBlocks(text) {
    // returns array of {lang, code} found in triple backticks ```lang\ncode```
    const blocks = [];
    const re = /```(\w+)?\n([\s\S]*?)```/g;
    let m;
    while ((m = re.exec(text)) !== null) {
      blocks.push({ lang: m[1] || "text", code: m[2].trim() });
    }
    return blocks;
  }

  function heuristicScore(text) {
    // very small heuristic: presence of code keywords + length
    let score = 0;
    if (!text) return 0;
    if (text.length > 120) score += 30;
    const codeMarkers = ["function", "def ", "class ", "return", "console.log", "#include", "std::"];
    codeMarkers.forEach(k => { if (text.includes(k)) score += 15; });
    return Math.min(100, score);
  }

  async function sendPrompt(rawPrompt) {
    const prompt = rawPrompt.trim();
    if (!prompt) return;
    pushMessage("user", prompt);
    setLoading(true);

    try {
      // call backend
      const res = await axios.post("http://localhost:5000/api/chat", { message: prompt }, { timeout: 60000 });
      let reply = res.data?.reply || "No response from AI";
      if (appendCopyright) reply += `\n\n© Mohammad Kavish`;
      pushMessage("assistant", reply);
      toast.success("AI replied ✅", { duration: 1500 });
    } catch (err) {
      console.error(err);
      const msg = err?.response?.data?.error || err.message || "Network error";
      pushMessage("assistant", `⚠️ Error: ${msg}`);
      toast.error("Failed to get response — check server console", { duration: 3000 });
    } finally {
      setLoading(false);
    }
  }

  function onSendClick() {
    // handle template substitution if template selected
    if (selectedTemplate) {
      const t = templates.find(x => x.id === selectedTemplate);
      const prepared = t.prompt.replace(/{lang}/g, "Python").replace(/{task}/g, input || "solve the problem").replace(/{code}/g, input || "");
      setSelectedTemplate("");
      setInput("");
      sendPrompt(prepared);
    } else {
      const text = input;
      setInput("");
      sendPrompt(text);
    }
  }

  function copyText(text) {
    navigator.clipboard.writeText(text).then(() => toast.success("Copied to clipboard"));
  }

  function downloadConversation() {
    const blob = new Blob([JSON.stringify(messages, null, 2)], { type: "application/json;charset=utf-8" });
    saveAs(blob, `kavish-conversation-${Date.now()}.json`);
  }

  function exportAsMarkdown() {
    let md = `# Kavish AI Conversation\nGenerated by Kavish AI — © Mohammad Kavish\n\n`;
    messages.forEach(m => {
      const t = new Date(m.time).toLocaleString();
      md += `**${m.role.toUpperCase()}** (${t})\n\n${m.text}\n\n---\n\n`;
    });
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    saveAs(blob, `kavish-conversation-${Date.now()}.md`);
  }

  // JS sandbox runner (very limited, runs in iframe)
  function runJS(code) {
    const iframe = document.createElement("iframe");
    iframe.sandbox = "allow-scripts";
    iframe.style.display = "none";
    document.body.appendChild(iframe);
    const win = iframe.contentWindow;
    try {
      win.eval(code);
      toast.success("Executed JS snippet in secure sandbox");
    } catch (e) {
      toast.error("JS execution error: " + e.message);
    }
    setTimeout(() => document.body.removeChild(iframe), 2000);
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-slate-900 to-black text-slate-100 p-6">
      <Toaster />
      <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Left column: controls */}
        <div className="md:col-span-1 bg-gray-900/40 rounded-2xl p-4 border border-gray-800">
          <h2 className="text-xl font-semibold mb-3">Kavish AI — Controls</h2>

          <div className="mb-3">
            <label className="block text-sm text-gray-300 mb-1">Templates</label>
            <div className="flex flex-wrap gap-2">
              {templates.map(t => (
                <button
                  key={t.id}
                  onClick={() => { setSelectedTemplate(t.id); toast("Template selected: " + t.label); }}
                  className={`px-3 py-1 rounded-md text-sm ${selectedTemplate === t.id ? "bg-blue-600" : "bg-gray-800/60"} hover:bg-blue-700`}
                >
                  {t.label}
                </button>
              ))}
            </div>
            <p className="text-xs text-gray-400 mt-2">Select a template then type details in the input area and press Send.</p>
          </div>

          <div className="mb-3">
            <label className="block text-sm text-gray-300 mb-1">Options</label>
            <div className="flex items-center gap-2">
              <input id="copyright" type="checkbox" checked={appendCopyright} onChange={e => setAppendCopyright(e.target.checked)} className="h-4 w-4" />
              <label htmlFor="copyright" className="text-sm text-gray-300">Append copyright © Mohammad Kavish</label>
            </div>
          </div>

          <div className="flex gap-2 mt-4">
            <button onClick={downloadConversation} className="flex-1 bg-emerald-600 hover:bg-emerald-700 py-2 rounded-lg">Download JSON</button>
            <button onClick={exportAsMarkdown} className="flex-1 bg-gray-700 hover:bg-gray-600 py-2 rounded-lg">Export MD</button>
          </div>

          <div className="mt-6 text-xs text-gray-400">
            <div>Evaluator: heuristic score for code quality</div>
            <div className="mt-3">Built by <strong>© Mohammad Kavish</strong></div>
          </div>
        </div>

        {/* Middle: Chat area */}
        <div className="md:col-span-2 bg-gradient-to-br from-slate-800/40 to-slate-900/30 rounded-2xl p-4 border border-gray-800 flex flex-col">
          <div className="flex items-center justify-between mb-4">
            <h1 className="text-2xl font-bold">⚡ Kavish AI Code Assistant</h1>
            <div className="text-sm text-gray-400">Connected to <span className="text-emerald-400">Groq</span></div>
          </div>

          <div className="flex-1 overflow-y-auto pr-2 space-y-4 mb-4">
            {messages.map((m, i) => (
              <div key={i} className={`max-w-full ${m.role === "user" ? "text-right" : "text-left"}`}>
                <div className={`${m.role === "user" ? "inline-block bg-blue-600/90 rounded-tr-lg rounded-bl-lg rounded-tl-lg" : "inline-block bg-gray-800/60 rounded-tl-lg rounded-br-lg rounded-tr-lg"} p-4`}>
                  <div className="prose prose-sm text-slate-100 break-words whitespace-pre-wrap">
                    {/* render code blocks specially */}
                    {(() => {
                      const blocks = extractCodeBlocks(m.text);
                      if (blocks.length === 0) return <div>{m.text}</div>;
                      return (
                        <div>
                          {/* render text before/after blocks simply */}
                          {/* If blocks exist, split by triple backticks to keep plain text too */}
                          {m.text.split(/```[\s\S]*?```/g).map((chunk, idx) => (
                            <div key={idx} className="mb-2">{chunk}</div>
                          ))}
                          {blocks.map((b, idx) => (
                            <div key={idx} className="mb-2">
                              <div className="flex items-center justify-between mb-1">
                                <div className="text-xs text-gray-300 font-medium">{b.lang}</div>
                                <div className="flex gap-2">
                                  <button onClick={() => copyText(b.code)} className="text-xs px-2 py-1 bg-gray-700 rounded">Copy</button>
                                  <button onClick={() => { const blob = new Blob([b.code], { type: "text/plain;charset=utf-8" }); saveAs(blob, `code-${idx}.${b.lang}`); }} className="text-xs px-2 py-1 bg-gray-700 rounded">Download</button>
                                  {b.lang === "javascript" && <button onClick={() => runJS(b.code)} className="text-xs px-2 py-1 bg-green-600 rounded">Run JS</button>}
                                </div>
                              </div>
                              <SyntaxHighlighter language={b.lang} style={atomOneDark} wrapLongLines={true}>
                                {b.code}
                              </SyntaxHighlighter>
                            </div>
                          ))}
                        </div>
                      );
                    })()}
                  </div>

                  <div className="text-xs text-gray-400 mt-2">{new Date(m.time).toLocaleTimeString()}</div>
                </div>

                {/* evaluation badge for assistant messages */}
                {m.role === "assistant" && (
                  <div className="mt-1">
                    <div className="text-xs inline-block bg-black/30 px-2 py-1 rounded text-gray-300">Quality: {heuristicScore(m.text)} / 100</div>
                  </div>
                )}
              </div>
            ))}
            <div ref={bottomRef} />
          </div>

          {/* input area */}
          <div className="pt-3 border-t border-gray-800">
            <div className="flex gap-2">
              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder={selectedTemplate ? "Enter details for the template..." : "Ask anything, or paste code to explain/refactor..."}
                className="flex-1 min-h-[64px] max-h-40 bg-gray-900/60 p-3 rounded-lg outline-none resize-none"
              />
              <div className="flex flex-col gap-2">
                <button onClick={onSendClick} disabled={loading} className="bg-blue-600 px-4 py-2 rounded text-white">
                  {loading ? "Generating..." : "Send"}
                </button>
                <button onClick={() => { setInput(""); setSelectedTemplate(""); }} className="bg-gray-700 px-3 py-2 rounded text-sm">Clear</button>
              </div>
            </div>

            <div className="mt-2 flex items-center justify-between text-xs text-gray-400">
              <div>Tip: Use triple backticks for code blocks. Example: <code>{'```python\nprint(\'hi\')\n```'}</code></div>
              <div className="flex gap-2">
                <button onClick={() => { navigator.clipboard.writeText(messages.map(m=>`${m.role}: ${m.text}`).join("\n\n")); toast.success("Copied full conversation"); }} className="px-2 py-1 bg-gray-800 rounded">Copy All</button>
                <button onClick={() => { setMessages([]); toast("Conversation cleared"); }} className="px-2 py-1 bg-red-700 rounded">Clear</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* footer */}
      <footer className="max-w-4xl mx-auto mt-6 text-center text-xs text-gray-500">
        Built & Copyright © Mohammad Kavish — Kavish AI Assistant — For demos & interviews.
      </footer>
    </div>
  );
}
